version: "3.7"
services:
  caddy:
    volumes:
      - personal-website-data:/data
    build:
      context: .
      target: dev
    ports:
      - 80:80
      - 443:443
      - 2019:2019

volumes:
  personal-website-data:
